# 3. Publicar/Empaquetar los archivos usando un comando de script nativo más directo
- script: |
    dotnet publish **/*.csproj --configuration Release --output "$(Build.ArtifactStagingDirectory)"
  displayName: 'Generar archivos ejecutables (Publish)'

# 4. Subir el archivo empaquetado a la nube de Azure
- task: PublishBuildArtifacts@1
  displayName: 'Subir artefacto a la nube de Azure'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'sinpe-bridge-backend-build'
    publishLocation: 'Container'