trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'

steps:
# 1. Restaurar las dependencias del proyecto
- task: DotNetCoreCLI@2
  displayName: 'Restaurar paquetes NuGet (.NET)'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 2. Compilar el Backend en modo Release
- task: DotNetCoreCLI@2
  displayName: 'Compilar Backend (Build)'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 3. IR A LO SEGURO: Copiar directamente la carpeta 'bin' donde se guardó la compilación exitosa
- task: CopyFiles@2
  displayName: 'Generar archivos ejecutables (Recopilar carpetas bin)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/bin/Release/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# 4. Subir el artefacto compilado a la nube de Azure
- task: PublishBuildArtifacts@1
  displayName: 'Subir artefacto a la nube de Azure'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'sinpe-bridge-backend-build'
    publishLocation: 'Container'